# Generated by Django 2.2.5 on 2020-02-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_remove_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.IntegerField(null=True),
        ),
    ]
