# Generated by Django 2.2.5 on 2020-02-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_start_time', models.CharField(max_length=50)),
                ('event_end_time', models.CharField(max_length=50)),
                ('event_sign_up_time', models.CharField(max_length=50)),
                ('event_localtion', models.CharField(max_length=200)),
                ('event_max_number', models.IntegerField(max_length=200)),
                ('event_now_number', models.IntegerField(null=True)),
                ('event_starter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login_register.User')),
            ],
        ),
        migrations.CreateModel(
            name='event_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_nichen', models.CharField(max_length=50)),
                ('member_real_name', models.CharField(max_length=50)),
                ('member_tel', models.CharField(max_length=50)),
                ('member_qq', models.CharField(max_length=50)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.event')),
            ],
        ),
        migrations.CreateModel(
            name='event_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_detail', models.TextField(null=True)),
                ('event_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='index.event')),
            ],
        ),
    ]
