# Generated by Django 2.2.5 on 2020-02-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_remove_user_permission'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_mem',
            field=models.ManyToManyField(null=True, related_name='man_joined', through='index.event_members', to='login_register.User'),
        ),
        migrations.AddField(
            model_name='event_members',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_max_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starter', to='login_register.User'),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='event_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.event'),
        ),
    ]
