# Generated by Django 2.2.5 on 2020-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200214_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_max_number',
            field=models.IntegerField(null=True),
        ),
    ]
