# Generated by Django 2.2.5 on 2020-02-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200218_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details',
            name='event_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.event'),
        ),
    ]
