# Generated by Django 2.2.5 on 2020-02-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200219_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_zu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
